version: '3'

services:
  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./project:/usr/share/nginx/html
    ports:
      - "3000:3000"
